import { MuelleTurno } from "@/core/domain/entities";
import { MuelleTurnoResponseDto } from "@/infrastructure/dtos/tenant/arly-1";
import { MuelleTurnoEntity } from "@/infrastructure/persistence/tenant/arly1";

export class MuelleTurnoMapper {
  public toResponseDto(muelleTurno: MuelleTurno): MuelleTurnoResponseDto {
    return {
      idturno: muelleTurno.idturno,
      idcliente: muelleTurno.idcliente,
      nombrecliente: muelleTurno.nombrecliente,
      direccioncliente: muelleTurno.direccioncliente,
      telefono: muelleTurno.telefono,
      email: muelleTurno.email,
      tipopago: muelleTurno.tipopago,
      observacion: muelleTurno.observacion,
      idtipoactividad: muelleTurno.idtipoactividad,
      cantidadcolaborador: muelleTurno.cantidadcolaborador,
      minutos: muelleTurno.minutos,
      fechainicio: muelleTurno.fechainicio,
      horainicio: muelleTurno.horainicio,
      fechafin: muelleTurno.fechafin,
      horafin: muelleTurno.horafin,
      valoriva: muelleTurno.valoriva,
      porcentajeretencion: muelleTurno.porcentajeretencion,
      valorretencion: muelleTurno.valorretencion,
      porcentajereteica: muelleTurno.porcentajereteica,
      valorreteiva: muelleTurno.valorreteiva,
      valordescuento: muelleTurno.valordescuento,
      subtotal: muelleTurno.subtotal,
      total: muelleTurno.total,
      placa: muelleTurno.placa,
      nombreconductor: muelleTurno.nombreconductor,
      telefonoconductor: muelleTurno.telefonoconductor,
      fecharegistro: muelleTurno.fecharegistro,
      fechacierre: muelleTurno.fechacierre,
      estado: muelleTurno.estado,
      idempresa: muelleTurno.idempresa,
      idmuelle: muelleTurno.idmuelle,
      sede: muelleTurno.sede,
      colaboradores: muelleTurno.colaboradores,
      detalles: muelleTurno.detalles,
    };
  }
  public toDomain(entity: MuelleTurnoEntity): MuelleTurno {
    return new MuelleTurno(
      entity.idturno,
      entity.idcliente,
      entity.nombrecliente,
      entity.direccioncliente,
      entity.telefono,
      entity.email,
      entity.tipopago,
      entity.observacion,
      entity.idtipoactividad,
      entity.cantidadcolaborador,
      entity.minutos,
      entity.fechainicio,
      entity.horainicio,
      entity.fechafin, 
      entity.horafin,
      entity.valoriva,
      entity.porcentajeretencion,
      entity.valorretencion,
      entity.porcentajereteica,
      entity.valorreteiva,
      entity.valordescuento,
      entity.subtotal,
      entity.total,
      entity.idclienteinventario,
      entity.nombreclienteinventario,
      entity.direccionclienteinventario,
      entity.telefonoclienteinventario,
      entity.placa, 
      entity.nombreconductor,
      entity.telefonoconductor,
      entity.idusuarioregistra,
      entity.fecharegistro,
      entity.idusuariocierra,
      entity.fechacierre,
      entity.estado,
      entity.idempresa,
      entity.idsede,
      entity.idagenda,
      entity.fechainicioreal,
      entity.fechaanulacion,
      entity.idmuelle,
      entity.idformapago_eliminar,
      entity.fechaterminado,
      entity.horaterminado,
      entity.sede ,
      entity.colaboradores,
      entity.detalles,

    );
  }
}