export * from './cedi-user-role.entity';
export * from './permission.entity';
export * from './menu-item.entity';
export * from './module.entity';
export * from './cedi.entity';
export * from './role.entity';
export * from './user.entity';
export * from './arly-1-turno.entity';
export * from './arly-1-detalle-turno.entity';